### ISSUE TITLE
Lizenz?

### ISSUE THREAD

**Issue by kerstin** [Lotterleben/miniref#3]
Ahhh, vorgestern hab ich nach diesem Repo hier gesucht, ohne mehr zu wissen, dass ich auf GH bzw. nach nem Repo suchen hätte sollen. (Ich hatte eine dunkle Erinnerung daran, kürzlich Code betreffend Fußnoten gesehen zu haben.)

Nach neuerlicher Durchsicht macht es scheinbar aber nicht genau das, was ich gebraucht hätte. Wenn ich das Readme und den Beispieltext richtig verstehe, dann macht das Script, dass ein Text, der bereits mit "Fußnoten" (unnummerierten) geschrieben ist, diese nummeriert bekommt?

Würdest du ne Lizenz adden? Es ist wie gesagt eh nicht genau das, was ich such, aber es wär mir lieber, zu wissen, wie das geshared ist, bevor ich mir den Code näher anschau und am Ende vielleicht Anleihen nehme...

**Comment by Lotterleben** [comment]
Ja, der Code tut ziemlich genau das was du beschreibst. :) (Und die Verweise unten werden eben entsprechend sortiert).
Ich kümmer mich heut Abend um die Lizenz. 
Darf ich interessehalber fragen, was du vor hast? :)

**Comment by Lotterleben** [comment]
License added. :bowtie:

**Comment by kerstin** [comment]
Super, danke!

Ich hätt aktuell schon zum zweiten Mal innerhalb kurzer Zeit was gebraucht, das einen mit Links gespickten (im aktuellen Fall: HTML-formatierten; aber für Markdown wär sowas sicher auch brauchbar) Text in Plain Text umwandelt für ein Forward per Mail - aber eben mit allen Links auf diese Art, am Ende, aufgelistet statt mitten im Text.

Online gibt's zwar diverse Tools, die Letzteres können (die Links werden dann üblicherweise im Fließtext in Klammern gesetzt), aber meine erste - zugegebenermaßen nicht super intensive - Suche hat nichts für dieses Fußnoten-Format ergeben. Ich weiß auch gar nicht, woher diese Formatierweise genau kommt (LaTeX?), ich kenn das selbst nur von ein paar wenigen Leuten, die ihre Mails halt so schreiben - vielleicht konnt ich deshalb auch noch nix finden.

Jedenfalls ist mir dann das hier wieder eingefallen, und da ich eh mehr Python machen mag, aber bisher noch nicht wirklich viel gemacht hab damit (und das auch schon wieder länger her ist), dacht ich mir, dass ich mir hier vielleicht bissl was abschauen kann. (:

**Comment by kerstin** [comment]
Ha, Überschneidung! Danke für das super schnelle Adden - suuuperrrrr!!

**Comment by Lotterleben** [comment]
Ja, das sollte sich egtl easy umbauen lassen... Ich hab das mit den Link im text damals ausgelassen weil mir lange Links die Formatierung zerlegt hätten und ich es deshalb so angenehmer fand. Falls du Hilfe brauchst oder Bugs findest, sag Bescheid!

**Comment by kerstin** [comment]
Yay, MIT! Mag ich auch sehr gern.

Btw. GitHub empfiehlt generell auch sowas wie einen LICENSE.md-File - ist nicht zwingend, und ich mach's auch immer (zusätzlich) ins Script rein; ist glaub ich mehr so gedacht, dass es auf einen Blick aufs Repo gleich sichtbar ist (so wie z.B. README.md), aber wollt's nur erwähnt haben. (:

Und jaaa, meld mich, wenn ich was brauch oder was find. Danke nochmal!
