### ISSUE TITLE
Markers consisting of digits can lead to incorrect numbering in text

### ISSUE THREAD

**Issue by kerstin** [Lotterleben/miniref#5]
When a(n original) marker is made up of digits and the same digits are now used by a new(ly numbered) marker, this new marker gets overwritten again with the new number of the old marker made up of digits.

Example:
    
    This[^a] is some[^bcd] example text[^1], lorem ipsum blahblahblah.

    [^a] ref1
    [^bcd] ref2
    [^1] ref3

Should (and temporarily does) result in:

    This[^1] is some[^2] example text[^3], lorem ipsum blahblahblah.

    [^1] ref1
    [^2] ref2
    [^3] ref3

But actually ends up as:

    This[^3] is some[^2] example text[^3], lorem ipsum blahblahblah.

    [^1] ref1
    [^2] ref2
    [^3] ref3

**Comment by Lotterleben** [comment]
oh, thanks for pointing that out.. I'll fix it tonight. :)

**Comment by Lotterleben** [comment]
If I understand the bug correctly, this should only happen if the clashing markers are o the same line. anyway, should be fixed now! :)
